/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dreamteam_sqljbaseddb_repositories_NativeAdapter */

#ifndef _Included_com_dreamteam_sqljbaseddb_repositories_NativeAdapter
#define _Included_com_dreamteam_sqljbaseddb_repositories_NativeAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dreamteam_sqljbaseddb_repositories_NativeAdapter
 * Method:    delete
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dreamteam_sqljbaseddb_repositories_NativeAdapter_delete
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
